version: "2"

services:
  app:
    # build: .
    image: partidodelared/afiliaciones:latest
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    # volumes:
    #   - ${PWD}:/usr/src
    #   - /usr/src/node_modules
  db:
    image: mongo:3
