version: "2"

services:
  lb:
    image: ngnix
  app:
    build:
      context: .
      dockerfile: Dockerfile.produ
    image: partidodelared/afiliaciones:dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:3000"
    depends_on:
      - db
    # volumes:
    #   - ${PWD}:/usr/src
    #   - /usr/src/node_modules
  db:
    image: mongo:3
